/*
 * Golem Gateway API
 *
 * Golem Brass Gateway API for Golem Unlimited
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use hyper;
use hyper::header::HeaderValue;

pub struct Configuration<C: 'static + hyper::client::connect::Connect + 'static> {
    pub base_path: String,
    pub user_agent: Option<HeaderValue>,
    pub client: hyper::client::Client<C>,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
    // TODO: take an oauth2 token source, similar to the go one
}

pub type BasicAuth = (String, Option<String>);

pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl<C: 'static + hyper::client::connect::Connect> Configuration<C> {
    pub fn new(client: hyper::client::Client<C>) -> Configuration<C> {
        Configuration {
            base_path: "http://127.0.0.1:55001".to_owned(),
            user_agent: Some(
                hyper::header::HeaderValue::from_str("OpenAPI-Generator/1.0.0/rust").unwrap(),
            )
            .to_owned(),
            client,
            basic_auth: None,
            oauth_access_token: None,
            api_key: None,
        }
    }
}
