/* 
 * Golem Gateway API
 *
 * Golem Brass Gateway API for Golem Unlimited
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TaskType {
}

impl TaskType {
  pub fn new() -> TaskType {
    TaskType {
    }
  }

}

// TODO enum 
// List of TaskType
//const (
//  
//  
//  
//)


